platform: linux
image_resource:
  type: docker-image
  source:
    repository: yolo/gpdbdev
    tag: centos6
inputs:
  - name: gpdb_src
  - name: bin_orca
  - name: bin_xerces
  - name: bin_gpdb
outputs:
  - name: icg_output
run:
  path: gpdb_src/concourse/scripts/build_gpdb.py
  args:
    - --mode=planner
    - --gpdb_name=bin_gpdb
    - --action=test
    - --configure-option=--disable-gpcloud
params:
  BLDWRAP_POSTGRES_CONF_ADDONS: "fsync=off"
